version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: my-local-db
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_USER: gurwl1885
      MYSQL_PASSWORD: 983821mk
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:

